require("dotenv").config()

const express = require("express")
const cors = require("cors")
const app = express()
const initDB = require("./database/initDb")
const taskRouter = require("./controllers/taskRouter")
const answerRouter = require("./controllers/answerRouter")
const userRouter = require("./controllers/userRouter")
const corsOptions = require("./config/cors")
const notFound = require("./middleware/notFound")
const errorHandler = require("./middleware/errorHandler")
const pinoHttp = require("pino-http")
const logger = require("./config/logger")

app.use(pinoHttp({ logger }))
app.use(cors(corsOptions))
app.use(express.json())
initDB()
  .then(() => logger.info("DB initialized"))
  .catch((error) => {
    logger.error(error, "DB init failed")
    process.exit(1)
  })
app.use("/api/tasks", taskRouter)
app.use("/api/answers", answerRouter)
app.use("/api/users", userRouter)
app.use(notFound)
app.use(errorHandler)
module.exports = app
