const partInstructions = {
  title: "Natural Deduction: Assumptions and Discharge",
  introduction:
    "Every rule so far has moved forward from lines you already had. That is a real limit: none of those rules builds an implication, and none of them proves a negation. This lesson adds the three rules that can — →I, ¬I, and ∨E — along with reiteration, which supports them. What these have in common is that they all involve a temporary assumption: a line you write down without justification, use for a while, and then withdraw. Withdrawing it is called discharging, and it is what turns temporary work into a permanent result.",
  paragraphs: [
    "Suppose your only premise is Q and your goal is P → Q. Nothing in the forward rules can help: ∧I builds conjunctions, ∨I builds disjunctions, ¬E builds contradictions, and the elimination rules only take things apart. No forward rule produces an implication at all. The problem isn't that the proof is hard — it's that the goal describes a *conditional* claim, and a conditional says something about a situation you may never be able to establish. To prove it you have to enter that situation deliberately.",
    "An **assumption** is a line you write down with no justification, marked as an assumption rather than derived. Doing so opens a **box**: an indented region where that assumption is available. Everything inside the box depends on it. When the box closes, the assumption is **discharged** — it and every line inside the box become unusable, and the only thing that survives is the single conclusion drawn by the rule that closed it. Depth is what tracks this: an assumption is indented one level deeper than the line before it, and the box stays open until a line appears at the shallower level again.",
    "Lines outside a box can be cited from inside it — outer results stay available as you go deeper, just not the other way around. **Reiteration** copies such a line into the box anyway, citing the original. This seems pointless until you meet the discharge rules, which require the *last line of the box* to be a specific formula. If that formula was established outside the box, reiteration is how you bring it in so it can occupy that final position.",
    "**→-introduction (→I)** proves an implication. Assume the antecedent, derive the consequent inside the box, then close the box and write A → B, citing two lines the assumption that opened the box and the last line inside it. The assumption need not actually be used — if the consequent was already available, reiterate it and discharge anyway. That is sound because A → B claims only that B holds *whenever* A does, and if B holds outright then it certainly holds whenever A does.",
    "**Contradiction** builds the line the discharge rules look for. From A on one line and ¬A on another, write A ∧ ¬A, citing both. Either order works — ¬A ∧ A is equally valid — but the two sides must be exact negations of one another, not merely claims that feel incompatible. What counts is the shape: one side is the other with a ¬ in front of it. That means ¬P and ¬¬P form a perfectly good contradiction, ¬P ∧ ¬¬P, because the formula being negated there is ¬P. On its own the rule produces something guaranteed false, which is useless; its purpose is to sit as the last line of a box so ¬I can discharge it.",
    "**¬-introduction (¬I)** proves a negation. Assume A, derive a contradiction inside the box — any line of the form X ∧ ¬X, whether or not X is A itself — then close the box and write ¬A, citing the assumption line and the contradiction line. The reasoning is the one promised in the last lesson: a contradiction can never be true, so if assuming A leads to one, A cannot hold. This is the rule that gives contradictions their purpose.",
    "**∨-elimination (∨E)** uses a disjunction. A ∨ B tells you one of the two holds but not which, so to get anything from it you must show that both possibilities lead to the same place. Open a box assuming A and derive C; open a second box assuming B and derive the same C; then write C, citing five lines: the disjunction, then each box's assumption and last line. The two boxes are **siblings** — they sit at the same depth, one after the other, and the second one opening is what closes the first.",
    "Boxes can be **nested**. A goal like A → (B → C) needs two: assume A, then assume B inside it, derive C, and discharge twice — the inner →I builds B → C, and the outer one builds the whole thing. Each →I closes exactly one box, so two layers of implication take two separate applications. Inside the inner box, both assumptions are available; after the inner box closes, only its conclusion is.",
    "The most common error with these rules is citing a line inside a box that has already closed. Once discharged, those lines are gone — not because they were wrong, but because they were only ever conditional on an assumption that no longer stands. The related error is finishing a proof with a box still open: a goal proved at depth 1 is not proved, it is proved *given* an assumption you never withdrew. A finished proof ends at depth 0.",
    "Step 1: look at the goal's main connective and ask which rule builds it.\nStep 2: if it's →, assume the antecedent and make the consequent your new goal.\nStep 3: if it's ¬, assume the un-negated formula and make a contradiction your new goal.\nStep 4: if a premise is a disjunction, plan two boxes proving the same thing.\nStep 5: work forward inside the box using the rules from the last lesson, then discharge.",
  ],
  examples: [
    "A goal the forward rules cannot reach:\nPremise: Q\nGoal: P → Q\n1. Q          (premise)\n∧I gives Q ∧ Q. ∨I gives Q ∨ P.\nNo rule so far produces →, so the proof cannot start.",
    "The anatomy of a box:\n\n1. A  (premise)          depth 0\n2.  | P  (assumption)       depth 1  ← box opens\n3.  | ...       (rules apply here) depth 1\n4.  | Q  (...)              depth 1\n5. P → Q  (→I lines: 2,4)    depth 0  ← box closes\n\nAfter line 5 lines: 2–4 can no longer be cited.",
    "Reiteration:\n\n1. Q  (premise)\n2.  | P  (assumption)\n3.  | Q  (reiteration line: 1)\n\nLine 1 could have been cited directly from inside the box.\nReiteration is needed because →I requires Q on the box's *last* line.",
    "→-introduction (→I):\nPremise: Q\nGoal: P → Q\n\n1. Q  (premise)\n2.  | P  (assumption)\n3.  | Q  (reiteration line: 1)\n4. P → Q  (→I lines: 2,3)\n\nP is never used. The discharge is still valid.",
    "Contradiction:\nFrom A and ¬A, derive A ∧ ¬A\n1. P  (premise)\n2. ¬P  (premise)\n3. P ∧ ¬P  (contradiction lines: 1,2)\n\nThe negated side may itself be complex:\n1. ¬P  (premise)\n2. ¬¬P  (premise)\n3. ¬P ∧ ¬¬P  (contradiction lines: 1,2)",
    "¬-introduction (¬I):\nPremises: P → Q, ¬Q\nGoal: ¬P\n\n1. P → Q  (premise)\n2. ¬Q  (premise)\n3.  | P  (assumption)\n4.  | Q  (→E lines: 1,3)\n5.  | Q ∧ ¬Q  (contradiction lines: 4,2)\n6. ¬P  (¬I lines: 3,5)",
    "∨-elimination (∨E):\nPremises: P ∨ Q, P → R, Q → R\nGoal: R\n\n1. P ∨ Q  (premise)\n2. P → R  (premise)\n3. Q → R  (premise)\n4.  | P  (assumption)\n5.  | R  (→E lines: 2,4)\n6.  | Q  (assumption)\n7.  | R  (→E lines: 3,6)\n8. R  (∨E lines: 1,4,5,6,7)\n\nLine 6 opens the sibling box, which closes line 4's.",
    "Nested assumptions:\nGoal: P → (Q → (P ∧ Q))\n\n1.  | P  (assumption)\n2.  |  | Q  (assumption)\n3.  |  | P ∧ Q  (∧I lines: 1,2)\n4.  | Q → (P ∧ Q)  (→I lines: 2,3)\n5. P → (Q → (P ∧ Q))  (→I lines: 1,4)\n\nLine 3 cites line 1 from two levels in — outward citation is fine.",
    "Citing a discharged line:\n\n1.  | P  (assumption)\n2.  | P  (reiteration line: 1)\n3. P → P  (→I lines: 1,2)\n4. P  ✗ invalid — lines: 1 and 2 are inside a closed box\n\nIf line 4 were allowed, P would have been proved from nothing.",
    "A full proof combining both lessons:\nPremises: P → Q, Q → R\nGoal: P → R\n\n1. P → Q  (premise)\n2. Q → R  (premise)\n3.  | P  (assumption)\n4.  | Q  (→E lines: 1,3)\n5.  | R  (→E lines: 2,4)\n6. P → R  (→I lines: 3,5)",
  ],
  definitions: [
    "Assumption = A line written without justification, opening a box in which it is available",
    "Box (Scope) = The indented region where an assumption and everything derived from it lives",
    "Discharge = Closing a box, making its assumption and contents unusable and keeping only the rule's conclusion",
    "Reiteration = Copying an accessible outer line into the current box, citing the original",
    "→-Introduction (→I) = Assume A, derive B in the box, discharge to get A → B",
    "¬-Introduction (¬I) = Assume A, derive a contradiction in the box, discharge to get ¬A",
    "∨-Elimination (∨E) = From A ∨ B and two boxes assuming A and B that both derive C, conclude C",
    "Sibling Boxes = Two boxes at the same depth, one after the other, as required by ∨E",
    "Undischarged Assumption = An assumption whose box never closed; a proof ending inside one proves nothing",
  ],
  moduleName: "Assumptions-And-Discharge-Natural-Deduction",
}

export default partInstructions
