const partInstructions = {
  title: "Recursive Definitions: How Propositions Are Actually Built",
  introduction:
    "Before looking at semantic trees, it's worth stopping to examine something that's easy to take for granted: the very definition of a proposition. That definition says propositional symbols are propositions, and more complex propositions are built from simpler ones using connectives — but that phrasing raises a fair question. Doesn't 'simpler propositions' already assume you know what a proposition is? Is this circular? This lesson shows it isn't, by making explicit exactly how the definition builds up in stages, and this same staged structure is also what semantic trees will visually represent.",
  paragraphs: [
    "The definition of a proposition has two parts: a **base case** — every propositional symbol (p₀, p₁, p₂, ...) is a proposition — and a **recursive case** — if A and B are already propositions, then ¬A, (A ∧ B), (A ∨ B), (A → B), and (A ↔ B) are propositions too. The recursive case doesn't define a proposition in terms of *itself*; it defines a new, larger proposition strictly in terms of *smaller, already-established* ones. That distinction is what keeps the definition from being circular.",
    "To see this precisely, it helps to build the set of propositions in explicit stages, written Lₙ. Start with **L₀** — the set containing just the propositional symbols themselves, nothing else: L₀ = {pₙ : n ∈ ℕ}. This matches the base case exactly.",
    "Then **Lₙ₊₁** is built from Lₙ by applying every connective rule once to whatever's already in Lₙ: Lₙ₊₁ = Lₙ ∪ {¬A : A ∈ Lₙ} ∪ {(A∧B) : A,B ∈ Lₙ} ∪ {(A∨B) : A,B ∈ Lₙ} ∪ {(A→B) : A,B ∈ Lₙ} ∪ {(A↔B) : A,B ∈ Lₙ}. Every new formula in Lₙ₊₁ is built out of formulas that were already sitting in Lₙ — so building Lₙ₊₁ never requires knowing what Lₙ₊₁ itself contains.",
    "Because of this, Lₙ can be understood very concretely: it's exactly the set of propositions that can be built using **at most n connective-building steps** starting from bare symbols. L₀ has zero steps (just symbols). L₁ adds everything reachable in one step. L₂ adds everything reachable in two steps, and so on.",
    "The full set of propositions is then simply the union of every stage: L₀ ∪ L₁ ∪ L₂ ∪ ... — every Lₙ for every natural number n. Any specific proposition you can actually write down, no matter how deeply nested, only ever needs finitely many connective steps to build — so it's guaranteed to show up in some specific, finite Lₙ. Nothing here loops back on an undefined notion of 'proposition'; each stage is built purely from the finite, already-known stage before it.",
    "There's a second, equivalent way to arrive at the same set, using the idea of **closure**. If A is a set and f is a function from A to A, a subset B of A is said to be *closed under f* when applying f to anything in B lands you back inside B — you never escape B by applying f to its own elements. The set of propositions can be described as the smallest subset of all finite symbol-strings that's closed under negation and all four binary connectives simultaneously, starting from the propositional symbols. Instead of building it stage by stage, this view just asks: what's the smallest collection that already contains the symbols and can't be enlarged any further by applying any connective to its own members?",
    "Both descriptions — the staged union of L₀, L₁, L₂, ... and the closure-under-the-connectives description — pick out exactly the same set of propositions. The staged version is usually more useful in practice, because it gives a concrete number (which stage n a proposition first appears in), and that number is precisely what makes **induction on structure** possible: to prove something holds for every proposition, it's enough to prove it for L₀, then show that whenever it holds for everything in Lₙ, it also holds for everything newly added in Lₙ₊₁.",
    "Defining G through a chain of intermediate propositions:\nA = p0                    (Stage 0)\nB = p1                    (Stage 0)\nC = (A ∧ B)               (Stage 1, built from Stage 0)\nD = ¬C                    (Stage 2, built from Stage 1)\nE = p2                    (Stage 0)\nF = (D ∨ E)               (Stage 3, built from Stage 2)\nG = (F → C)               (Stage 4, built from Stage 3)",
  ],
  examples: [
    "Stage L₀:\np₀, p₁, p₂, ... are all in L₀ — nothing else is.",
    "Stage L₁, built from L₀:\nSince p₀, p₁ ∈ L₀, applying the connective rules once gives new formulas that appear in L₁ for the first time:\n¬p₀, (p₀ ∧ p₁), (p₀ ∨ p₁), (p₀ → p₁), (p₀ ↔ p₁)",
    "Stage L₂, built from L₁:\nSince (p₀ ∧ p₁) ∈ L₁, applying negation once more gives a formula that appears in L₂ for the first time:\n¬(p₀ ∧ p₁)\nThis formula could not have appeared in L₁, since (p₀ ∧ p₁) itself wasn't available until L₁ existed.",
    "Tracing a formula to its stage:\n((p₀ ∧ p₁) → ¬p₂)\nStep 1: p₀, p₁, p₂ ∈ L₀\nStep 2: (p₀ ∧ p₁) ∈ L₁, and ¬p₂ ∈ L₁\nStep 3: ((p₀ ∧ p₁) → ¬p₂) ∈ L₂, since both halves were already available in L₁\nSo this formula first appears in L₂ — built in exactly 2 connective-steps.",
    "Closure, in a simpler setting first:\nLet A = ℕ and f(x) = x + 1 (successor). The set {0, 1, 2, 3, ...} is closed under f, since adding 1 to any natural number gives another natural number — you never leave the set. A smaller set like {0, 1, 2} is not closed under f, since f(2) = 3 escapes it.",
    "Building up new propositions from named ones:\nLet A = p0 and B = p1 — both base symbols, so both are in L0.\nLet C = (A ∧ B) — combining A and B with ∧ gives a new proposition, in L1.\nLet D = ¬C — negating C gives another new proposition, in L2.\nLet E = p2 — another base symbol, in L0.\nLet F = (D ∨ E) — combining D and E with ∨ gives a new proposition, in L3.\nLet G = (F → C) — combining F and C with → gives a new proposition, in L4.\nNotice G reuses C, a proposition already built two stages earlier — nothing stops an earlier proposition from being used again later; the definition only requires that whatever's used already exists at an earlier or equal stage.",
    "Closure applied to propositions:\nThe set of all propositions is the smallest set of symbol-strings that contains every pₙ, and is closed under: A ↦ ¬A, and (A,B) ↦ (A∧B), (A,B) ↦ (A∨B), (A,B) ↦ (A→B), (A,B) ↦ (A↔B) — applying any of these to strings already in the set never produces a string outside the set.",
    "Expanding G down to base symbols:\nG = (F → C)\n= ((D ∨ E) → C)\n= ((¬C ∨ E) → C)\n= ((¬(A ∧ B) ∨ E) → (A ∧ B))\n= ((¬(p0 ∧ p1) ∨ p2) → (p0 ∧ p1))",
  ],
  definitions: [
    "Recursive (Inductive) Definition = A definition with a base case (the simplest objects) and a recursive case (how to build larger objects from ones already defined), avoiding circularity by only ever referring to already-established, simpler objects",
    "Base Case = The starting point of a recursive definition — here, the propositional symbols pₙ",
    "Recursive Case = The rule for building larger objects from smaller, already-defined ones — here, the five connective rules applied to existing propositions",
    "Lₙ (Stage n) = The set of all propositions buildable using at most n connective-building steps from bare symbols",
    "Closure (under a function/operation) = The smallest set containing a given base set that isn't enlarged by applying the operation(s) to its own members",
  ],
  moduleName: "Recursive-Definition",
}

export default partInstructions
