export const partInstructions = {
  1: {
    1: {
      title: "Turning natural language in to propositions",
      introduction:
        "Propositional logic is the foundation of computer science and formal reasoning. It allows us to take ambiguous real-world statements and translate them into precise mathematical formulas that a computer can evaluate with complete certainty. By stripping away language barriers, we can systematically test whether a complex argument or code condition is fundamentally true or false. To do this, we map simple declarative sentences to uppercase variable letters like P or Q, which we call propositions. We then connect them using logical operators.",
      paragraphs: [
        "**AND** statement is represented the by **∧**. If i say 'i overslept and i am late' it could be represented as",
        "**OR** statement is represented the by symbol **∨**. If i say 'i either overslept or i am early' it could be represented as",
        "**NOT** statement is represented the by symbol **¬**. I could also say 'i either overslept or i am not late' representing it as",
        "An **IF-THEN** conditional statement is represented by the arrow symbol **→**. If i want to say 'If i oversleep i will be late' i could write",
        `**IF AND ONLY IF** relationship uses the double-arrow symbol **↔**. This asserts that two statements are both true or both false at the sametime. 
      If i say 'I am only late when i oversleep and i only oversleep when i am late' i could write`,
        "**Parenthesis change the structure of the proposition.** By adding or changing them we also change the meaning. 'I am either early or i have overslept and i am late'",
        "If i swap the parenthesis we get this. *Can you see why it doesn't make sense?*",
      ],
      examples: [
        "O ∧ L",
        "O ∨ E",
        "O ∨ ¬L",
        "O → L",
        "O ↔ L",
        "E ∨ (O ∧ L)",
        "(E ∨ O) ∧ L",
      ],
      definitions: ["O = 'I oveslept'", "L = 'I am late'", "E = 'I am early'"],
      moduleName: "words-to-propositions",
    },
    2: {
      title: "Deconstructing Propositions into Subformulas",
      introduction:
        "When evaluating a complex logical expression, a computer doesn't read the whole string at once. It breaks the proposition down into a hierarchy of smaller pieces called subformulas. Understanding how to split a formula into its component branches is the secret to building truth tables, parsing syntax errors, and understanding exactly how data flows through a logic gate network.",
      paragraphs: [
        "**Every logic formula has a Main Connective, which is the very last operator applied when evaluating the statement.** To find subformulas, we identify this operator and split the statement at that exact point. If our main operator is a **Binary Operator** like AND, OR, Implication, or Biconditional, it requires two inputs. Therefore, it splits the proposition into two distinct subformula branches: a left child and a right child.",
        "In contrast, the Negation symbol is a **Unary Operator**, meaning it only acts upon a single input that follows it. When a negation is the main connective of a subformula, it does not split the logic into two paths. Instead, it creates a single, straight downward branch that strips away the NOT symbol to evaluate the inner proposition directly underneath it.",
        "**Parentheses are the ultimate authority in determining how a formula splits.** They act as protective shields, forcing the operators inside them to cluster together. An operator inside parentheses cannot be the main connective of the outer expression. By shifting where the brackets sit, you completely alter which operator is exposed as the root, changing a double-branch split into a single-branch split, or vice versa.",
        "By continuously repeating this splitting process on every subformula until only individual variable letters remain, you create a **Syntax Tree**. The individual variables at the very bottom are the atomic subformulas, which cannot be split any further. Here is what a complete fully-deconstructed formula tree looks like when all the rules are applied together.",
      ],
      examples: [
        "Expression: P ∧ Q\n\n      [ ∧ ] (Main)\n      /   \\\n    [P]   [Q]",
        "Expression: ¬(P ∨ Q)\n\n      [ ¬ ] (Main)\n        |\n      [ ∨ ]\n      /   \\\n    [P]   [Q]",
        "Expression A: ¬P ∧ Q (Main is ∧)\nExpression B: ¬(P ∧ Q) (Main is ¬)",
        "Expression: (P → Q) ∧ ¬R\n\n          [ ∧ ]\n         /     \\\n      [ → ]   [ ¬ ]\n      /   \\     |\n    [P]   [Q]  [R]",
      ],
      definitions: [
        "Binary Operators = ∧, ∨, →, ↔ (Create 2 branches)",
        "Unary Operators = ¬ (Creates 1 branch)",
        "Atomic Formulas = Individual variables like P, Q, R (Base leaves)",
        "Syntax Tree = A diagram that breaks a formula into its subformulas, showing how connectives combine variables into the full expression",
      ],
      moduleName: "subformula",
    },
    3: {
      title: "Truth Tables: Testing Every Logical Case",
      introduction:
        "A truth table is a complete map of a logical formula. Instead of checking only one example input, we test every possible True/False combination for its atomic variables. This guarantees that we can see exactly when a formula is true, when it is false, and whether two formulas always match each other.",
      paragraphs: [
        "To build a truth table, first list every atomic variable in the formula. If there are n variables, the table must have 2^n rows. For example, with P and Q we need 4 rows: 11, 10, 01, 00. **These rows represent every possible situation the formula can be evaluated in.**",
        "Truth tables are useful because they remove guessing. You can prove whether an argument is valid, check if a formula is a **tautology** (always true), **contradiction** (always false), or **contingency** (sometimes true, sometimes false), and compare two formulas to see if they are **logically equivalent.**",
        "**Negation** (¬) flips the value of a single variable. Whatever P is, ¬P is the opposite. This is the only symbol that works on one variable instead of combining two.",
        "**Conjunction** (∧) combines two variables and is only true when both sides are true. If even one side is false, the whole conjunction becomes false.",
        "**Disjunction** (∨) combines two variables and is true when at least one side is true. It is only false when both sides are false.",
        "**Implication** (→) says that if the left side is true, the right side must also be true. The only case where an implication fails is when the left side is true but the right side is false; in every other case it holds.",
        "**Biconditional** (↔) is true whenever both sides have the same value, whether that is true or false. It fails whenever the two sides disagree.",
        "The fastest way to fill a truth table is to use **subformulas** as helper columns. Instead of evaluating a large formula in one jump, compute the inner parts first and reuse those results. This reduces mistakes and mirrors how a computer evaluates expressions step by step.",
        "Step 1: take the formula (P → Q) ∧ ¬P and list the atomic variables P and Q.\nStep 2: make the base rows represent all combinations.\nStep 3: combine the atomic variables with their parent symbol from the subformula tree.\nStep 4: calculate the value for this and add it to the table.\nStep 5: Continue this recursively until you have the original proposition and its truth values.",
      ],
      examples: [
        "Variable rows for P and Q:\n\nP | Q\n1 | 1\n1 | 0\n0 | 1\n0 | 0",
        "Use cases:\n- Validity checking\n- Tautology testing\n- Equivalence checking",
        "Truth table for ¬P:\n\nP | ¬P\n1 |  0\n0 |  1",
        "Truth table for P ∧ Q:\n\nP | Q | P ∧ Q\n1 | 1 |   1\n1 | 0 |   0\n0 | 1 |   0\n0 | 0 |   0",
        "Truth table for P ∨ Q:\n\nP | Q | P ∨ Q\n1 | 1 |   1\n1 | 0 |   1\n0 | 1 |   1\n0 | 0 |   0",
        "Truth table for P → Q:\n\nP | Q | P → Q\n1 | 1 |   1\n1 | 0 |   0\n0 | 1 |   1\n0 | 0 |   1",
        "Truth table for P ↔ Q:\n\nP | Q | P ↔ Q\n1 | 1 |   1\n1 | 0 |   0\n0 | 1 |   0\n0 | 0 |   1",
        "Expression: (P → Q) ∧ ¬P\n\n          [ ∧ ]\n         /     \\\n      [ → ]   [ ¬ ]\n      /   \\     |\n    [P]   [Q]  [P]",
        "Truth table for (P → Q) ∧ ¬P:\n\nP | Q | P → Q | ¬P | (P → Q) ∧ ¬P\n1 | 1 |   1   |  0 |       0\n1 | 0 |   0   |  0 |       0\n0 | 1 |   1   |  1 |       1\n0 | 0 |   1   |  1 |       1",
      ],
      definitions: [
        "Truth Table = A table listing every variable assignment and resulting formula value",
        "Validity = An argument is valid if there is no row where all premises are true and the conclusion is false",
        "Tautology = Formula that is true on every row",
        "Contradiction = Formula that is false on every row",
      ],
      moduleName: "Truth-Table-Task",
    },
    4: {
      title:
        "Equivalence Rules: Rewriting Propositions Without Changing Their Meaning",
      introduction:
        "Many logical formulas that look different are actually saying the same thing. An equivalence rule lets us rewrite a proposition into another form while keeping its truth value identical in every possible case. This is useful for simplifying formulas, comparing them, or preparing them for further logical work.",
      paragraphs: [
        "Two formulas are **logically equivalent** (written A ≡ B) if they have the same truth value in every row of their truth table. If you swap one for the other anywhere inside a larger formula, the meaning of the whole formula does not change. This is the foundation of every rewriting rule in this lesson.",
        "**Double negation** removes a pair of negations sitting in front of the same variable. If a formula is negated twice, the two negations cancel out and only the original variable remains.",
        "**Implication elimination** rewrites an arrow (→) as a disjunction. An implication P → Q is only false when P is true and Q is false, which is exactly the same condition under which ¬P ∨ Q is false. So the two forms always match.",
        "**Biconditional elimination** rewrites a ↔ symbol using connectives we already know how to work with. It can be split into two implications that must both hold, or into a disjunction of two conjunctions describing the cases where both sides agree.",
        "The **contrapositive** reverses an implication and negates both sides. P → Q and ¬Q → ¬P always share the same truth value, even though they read in opposite directions. This rule is often used to make an implication easier to prove or evaluate.",
        "**De Morgan's laws** describe what happens when a negation is pushed through a conjunction or disjunction. Negating an AND flips it into an OR of negations, and negating an OR flips it into an AND of negations. In both cases the negation moves inward, the connective switches, and each individual variable gets negated.",
        "Step 1: identify which connective is on the outside of the part you want to rewrite (¬, →, ↔, ∧, or ∨).\nStep 2: pick the matching equivalence rule for that connective.\nStep 3: rewrite only that part, keeping the rest of the formula untouched.\nStep 4: if a negation now sits in front of a new ∧ or ∨, check whether De Morgan's law can be applied again.\nStep 5: repeat until no more rules apply or the formula reaches the form you need.",
      ],
      examples: [
        "Logical equivalence:\nA ≡ B means A and B have identical truth values in every row of their truth table.",
        "Double negation:\n¬¬P ≡ P",
        "Implication elimination:\nP → Q ≡ ¬P ∨ Q",
        "Biconditional elimination:\nP ↔ Q ≡ (P → Q) ∧ (Q → P)\nP ↔ Q ≡ (P ∧ Q) ∨ (¬P ∧ ¬Q)",
        "Contrapositive:\nP → Q ≡ ¬Q → ¬P",
        "De Morgan's laws:\n¬(P ∧ Q) ≡ ¬P ∨ ¬Q\n¬(P ∨ Q) ≡ ¬P ∧ ¬Q",
        "Worked example:\n¬(P → Q)\n[implication elimination]\n≡ ¬(¬P ∨ Q)\n[De Morgan's law]\n≡ ¬¬P ∧ ¬Q\n[double negation]\n≡ P ∧ ¬Q",
      ],
      definitions: [
        "Logical Equivalence = Two formulas that have identical truth values in every row of their truth table (A ≡ B)",
        "Conjunction = A formula joined by ∧ (AND) that is true only when both sides are true",
        "Disjunction = A formula joined by ∨ (OR) that is true when at least one side is true",
        "Contrapositive = Reversing and negating both sides of an implication: P → Q ≡ ¬Q → ¬P",
        "De Morgan's Laws = Rules for pushing a negation through ∧ or ∨, switching the connective and negating each part",
      ],
      moduleName: "Equivalence-Rules-Task",
    },
    5: {
      title: "Part 1 Complete: From Natural Language to Logical Equivalence",
      introduction:
        "Congratulations on completing Part 1! Over the last few lessons, we covered the foundation that all of propositional logic rests on. These skills will become more and more important as we move towards reasoning in Part 2.",
      paragraphs: [
        'We covered turning **natural language into propositions**. Sentences like "if it rains, the ground gets wet" become formal expressions like P → Q. This translation step matters because logic can only operate on precise, unambiguous statements — English is full of implicit meaning that formal notation forces you to make explicit.',
        "We also covered how to **deconstruct propositions into their subformulas**. A formula like ¬(P ∧ Q) → R is not one indivisible thing; it is built from smaller pieces (P, Q, P ∧ Q, ¬(P ∧ Q)) connected by operators. Being able to identify these pieces is what lets you analyze, evaluate, or rewrite a formula rather than just staring at it as a whole.",
        "Next was **truth tables**, which give you a way to determine exactly when a formula is true or false, for every possible combination of its variables. Truth tables are the ground truth of logic — every other rule or shortcut is only valid because it agrees with what the truth table says.",
        "Finally, we covered rewriting propositions into **equivalent forms** using rules like double negation, implication elimination, biconditional elimination, the contrapositive, and De Morgan's laws. These rules let you transform a formula without changing its meaning, which is essential for simplifying expressions or putting them into a shape that's easier to work with.",
        "**Part 2** builds directly on all of this. The **resolution method** is a systematic proof technique that works by breaking formulas into subformulas, rewriting them into a standard equivalent form, and then combining pieces to detect contradictions — every step depends on the skills covered above.",
        "Part 2 also introduces the **semantic tree** method, which organizes the process of checking every truth-value combination of a formula into a branching tree structure. It's essentially a more efficient, visual alternative to building a full truth table, so the intuition built around truth tables carries over directly.",
        "In short: Part 1 provided the vocabulary and tools; Part 2 shows how to use them to actually prove things. Without comfort in translation, decomposition, truth tables, and equivalence, the methods in Part 2 would just look like arbitrary symbol shuffling.",
      ],
      examples: [
        'Translation skill in action:\n"Either the alarm is broken, or someone is home" → ¬A ∨ H',
        "Decomposition skill in action:\n(P ∧ Q) → ¬R has subformulas: P, Q, P ∧ Q, R, ¬R",
        "Truth table skill in action:\nP → Q is false only when P = true and Q = false",
        "Equivalence skill in action:\n¬(P → Q) ≡ P ∧ ¬Q",
        "Preview of Part 2 — resolution method:\nRewrite formulas into clauses, then combine contradictory clauses to prove a conclusion follows",
        "Preview of Part 2 — semantic tree:\nBranch a formula into true/false cases, closing branches that lead to contradictions",
        "Good Luck 😃",
      ],
      definitions: [
        "Proposition = A declarative statement that is either true or false, expressed formally using variables and connectives",
        "Subformula = A smaller formula contained within a larger formula, formed by one of its connectives",
        "Truth Table = A table listing every combination of truth values for a formula's variables, alongside the formula's resulting truth value",
        "Resolution Method = A proof technique that combines equivalent, rewritten clauses to detect contradictions and establish logical conclusions",
        "Semantic Tree = A branching diagram used to test every possible truth assignment of a formula, closing branches that produce contradictions",
      ],
    },
  },
  2: {
    1: {
      title: "Normal Forms: Converting Propositions to DNF and CNF",
      introduction:
        "A normal form is a standardized shape that any proposition can be rewritten into. Two of the most useful shapes are disjunctive normal form (DNF) and conjunctive normal form (CNF). Putting a formula into one of these forms doesn't change what it means — it just makes its structure predictable, which is exactly what later logical procedures need. CNF in particular will be the required input format for the resolution method coming up, so getting comfortable producing it is worth extra attention here. There are two common ways to derive a normal form: the truth-table method and the equivalence-rule method. This lesson covers the truth-table method; the equivalence-rule method is covered in the next section.",
      paragraphs: [
        "A **literal** is a variable or its negation — P and ¬P are both literals, but ¬¬P or P ∧ Q are not. Every normal form is built out of literals combined in a specific pattern.",
        "**Disjunctive normal form (DNF)** is a disjunction of conjunctions of literals — an OR of AND-groups, such as (P ∧ Q) ∨ (¬P ∧ R). Each parenthesized group is sometimes called a conjunctive clause.",
        "**Conjunctive normal form (CNF)** is a conjunction of disjunctions of literals — an AND of OR-groups, such as (P ∨ Q) ∧ (¬P ∨ R). Each parenthesized group is called a disjunctive clause, or just a clause. This is the form the resolution method operates on directly, since resolution works by combining pairs of clauses.",
        "The **truth-table method** builds the full truth table for the proposition, then reads the normal form directly off the rows where the formula lands on a particular value. For DNF, look at every row where the formula is 1. For each of those rows, write a conjunction of the variables, using the variable itself if it's 1 in that row and its negation if it's 0. Then join all of those conjunctions with ∨.",
        "For CNF, the process mirrors DNF but starts from the rows where the formula is 0. For each such row, write a disjunction of the variables, but flip the sign of each one: use the negation if the variable is 1 in that row, and the variable itself if it's 0. Then join all of those disjunctions with ∧.",
        "This flip is the part that catches people off guard the first time. It makes sense once you check it against the truth table: a disjunctive clause is false only when every literal inside it is false, so to make a clause that's false on exactly one specific row, each literal in it has to be the opposite of what's true in that row.",
        "Step 1: build the full truth table for the proposition.\nStep 2: decide whether you're building DNF or CNF.\nStep 3 (DNF): for every row where the formula is 1, write a conjunction of literals matching that row's values directly.\nStep 3 (CNF): for every row where the formula is 0, write a disjunction of literals with each value flipped.\nStep 4: join the clauses from step 3 with ∨ (for DNF) or ∧ (for CNF).\nStep 5: if there are no rows equal to 1, the DNF is simply a contradiction; if there are no rows equal to 0, the CNF is simply a tautology.",
        "The truth-table method is mechanical and hard to get wrong, since it never requires spotting which rewrite rule applies — but it can produce long formulas when a proposition has many variables or many 1/0 rows. The equivalence-rule method, covered next, usually reaches a shorter result but takes more practice to apply correctly.",
      ],
      examples: [
        "Literal:\nP and ¬P are literals. ¬¬P and P ∧ Q are not.",
        "DNF example:\n(P ∧ Q) ∨ (¬P ∧ R)",
        "CNF example:\n(P ∨ Q) ∧ (¬P ∨ R)",
        "Truth table for P ∧ (Q ∨ R):\n\nP | Q | R | P ∧ (Q ∨ R)\n1 | 1 | 1 |      1\n1 | 1 | 0 |      1\n1 | 0 | 1 |      1\n1 | 0 | 0 |      0\n0 | 1 | 1 |      0\n0 | 1 | 0 |      0\n0 | 0 | 1 |      0\n0 | 0 | 0 |      0",
        "Worked example — DNF from the table above:\nRows equal to 1: (1,1,1), (1,1,0), (1,0,1)\nDNF: (P ∧ Q ∧ R) ∨ (P ∧ Q ∧ ¬R) ∨ (P ∧ ¬Q ∧ R)",
        "Worked example — CNF from the same table:\nRows equal to 0: (1,0,0), (0,1,1), (0,1,0), (0,0,1), (0,0,0)\nFlipping each row's values and joining with ∨ inside, ∧ between:\n(¬P ∨ Q ∨ R) ∧ (P ∨ ¬Q ∨ ¬R) ∧ (P ∨ ¬Q ∨ R) ∧ (P ∨ Q ∨ ¬R) ∧ (P ∨ Q ∨ R)",
      ],
      definitions: [
        "Literal = A variable or its negation (P or ¬P)",
        "Disjunctive Normal Form (DNF) = A disjunction of conjunctions of literals, e.g. (P ∧ Q) ∨ (¬P ∧ R)",
        "Conjunctive Normal Form (CNF) = A conjunction of disjunctions of literals, e.g. (P ∨ Q) ∧ (¬P ∨ R)",
        "Clause = A single disjunction of literals within a CNF formula",
        "Truth-Table Method = Deriving a normal form by reading DNF off the rows equal to 1 or CNF off the rows equal to 0 (with each literal's sign flipped) of a formula's truth table",
      ],
      moduleName: "Normal-Forms-Task",
    },
  },
}
